# Generated by Django 4.2 on 2023-04-30 05:56

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='News/')),
                ('text', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(default=datetime.date)),
            ],
        ),
    ]
