# Generated by Django 4.2 on 2023-04-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Liga/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Liga/')),
                ('tur', models.IntegerField(default=1)),
                ('nisbat', models.IntegerField(default=1)),
                ('ochko', models.IntegerField(default=1)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.liga')),
            ],
        ),
        migrations.CreateModel(
            name='OldGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natija', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.liga')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_games_player1', to='football.team')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_games_player2', to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='NewGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.liga')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_games_player1', to='football.team')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_games_player2', to='football.team')),
            ],
        ),
    ]
