# Generated by Django 4.2 on 2023-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='nisbat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='ochko',
            field=models.IntegerField(default=0),
        ),
    ]
