# Generated by Django 4.2 on 2023-04-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_team_nisbat_alter_team_ochko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tur',
            field=models.IntegerField(default=0),
        ),
    ]
